name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.0.2']
        cabal: ['3.8.1.0']
        os: [ubuntu-latest, windows-latest]
    name: ${{ matrix.resolver }} (${{ matrix.ghc }}/${{ matrix.cabal }})
    steps:

      - name: Check out
        uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
          enable-stack: false

      - name: Versions
        run: |
          cabal --version
          ghc --version

      - name: Update
        run: |
          cabal update

      - name: Build
        run: |
          cabal build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          path: ${{ github.workspace }}/dist/newstyle/build/*
